language: node_js
node_js:
  - '8'
  - '7'
  - '6'

cache:
  directories:
    - node_modules

script:
  - yarn build
  - yarn test
  - yarn lint
  - yarn test-parser

deploy:
  provider: npm
  email: "$NPM_AUTH_EMAIL"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    tags: true
    node_js: '8'
  skip_cleanup: true
